name: club_blackout
description: Club Blackout (Flutter)
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  shared_preferences: ^2.2.3
  sensors_plus: ^7.0.0
  wakelock_plus: ^1.2.8
  dynamic_color: ^1.7.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  cross_file: ^0.3.4+2
  flutter_displaymode: ^0.7.0
  provider: ^6.1.5+1
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  path: ^1.9.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon_black.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon_black.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/roles.json
    - Backgrounds/Club Blackout V2 Game Background.png
    - Backgrounds/Club Blackout V2 Home Menu.png
    - Icons/Icon-No text-Ally Cat-Lemon.webp
    - Icons/Icon-No text-Bartender-Indigo.webp
    - Icons/Icon-No text-Bouncer-Blue.webp
    - Icons/Icon-No text-Clinger-Yellow.webp
    - Icons/Icon-No text-Club Manager-Taupe.webp
    - Icons/Icon-No text-Creep-Purple.webp
    - Icons/Icon-No text-Dealer-Fuschia.webp
    - Icons/Icon-No text-Drama Queen-Navy.webp
    - Icons/Icon-No text-Lightweight-Orange.webp
    - Icons/Icon-No text-Medic-Red.webp
    - Icons/Icon-No text-Messy Bitch-Lavender.webp
    - Icons/Icon-No text-Minor-White.webp
    - Icons/Icon-No text-Party Animal-Peach.webp
    - Icons/Icon-No text-Predator-Grey.webp
    - Icons/Icon-No text-Roofi-Green.webp
    - Icons/Icon-No text-Seasoned Drinker-Mint.webp
    - Icons/Icon-No text-Second Wind-Cherry.webp
    - Icons/Icon-No text-Silver Fox-Olive.webp
    - Icons/Icon-No text-Sober-Lime.webp
    - Icons/Icon-No text-Tea Spiller-Gold.webp
    - Icons/Icon-No text-Wallflower-Pink.webp
    - Icons/Icon-No text-Whore-Teal.webp

  fonts:
    - family: NeonGlow
      fonts:
        - asset: assets/fonts/NEON GLOW-Hollow.otf
